### ISSUE TITLE
이벤트 삭제 관련 질문 드립니다.

### ISSUE THREAD

**Issue by binlee52** [boostcamp-AI-Tech-alumni/Events#13]
안녕하세요, 부스트캠프 2기 이한빈입니다.
Events wiki 관리 방법에 관해 질문드립니다.

기한이 지난 이벤트(특강, 컨퍼런스, 경진대회) (EX. 2022 국립국어원 인공지능 언어 능력 평가 대회)는 README에서 단순하게 삭제하면 될까요?

**Comment by thepenielcho** [comment]
@binlee52 안녕하세요, 한빈님!

먼저 이슈 오픈해주셔서 감사합니다 🙇🏻‍♂️

마감된 이벤트의 경우 삭제가 아닌 아카이빙을 진행합니다! 기존에는 어느 정도 이벤트가 쌓일 경우 별도 파일에 분리하여 아카이빙을 하고자 했으나, 현재 별도 파일로 분류할 만큼의 양이 쌓였다고 판단하기는 힘들어 `<details>` 태그를 통해 Toggle을 만들어 숨김처리 하는 방식으로 처리해두었습니다.

추후 한빈님께서 기여해주신 이벤트가 종료/마감되었을 경우, `<details>` 태그 내로 해당 이벤트를 옮겨주시면 감사하겠습니다ㅎㅎ

지속적인 참여 감사드립니다!
